export enum MOSAIC_COMPONENT_NAME {
  SCENE_TOOLBAR = 'scene_toolbar',
  BOARD = 'board',
  CONSOLE = 'console',
  STORY_DIAGRAM = 'story_diagram',
  STORY_TOOLBAR = 'story_toolbar',
  STORY_EDIT_NODE = 'story_edit_node',
  EDIT_AGENT_INSTANCE = 'edit_agent_instance',
  FOLDER_EXPLORER = 'folder_explorer',
  PROJECT_WORKSPACE = 'project_workspace',
  PROJECT_METADATA = 'project_metadata',
  PROJECT_DATA = 'project_data',
  EDIT_AGENT_CLASS = 'edit_agent_class',
  KNOWLEDGE_BASE_GRAPH = 'knowledge_base_graph',
}